# Generated by Django 5.2.4 on 2025-07-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='workspace_id',
            field=models.CharField(default='default-id', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
