# Generated by Django 5.2.4 on 2025-07-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('accuracy', models.FloatField()),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('input_features', models.JSONField()),
                ('model_path', models.TextField()),
            ],
        ),
    ]
